# SEE: https://github.com/remiprev/teamocil
name: code_fund_ads
windows:
  - name: vim
    root: /path/to/project
    layout: main-vertical
    panes:
      - commands:
        - asdf local ruby 2.6.1
        - asdf local nodejs 9.11.2
        - nvim
        focus: true

  - name: console
    root: /path/to/project
    layout: main-vertical
    panes:
      - commands:
        - asdf local ruby 2.6.1
        - asdf local nodejs 9.11.2
        - bundle exec rails c

  - name: rails
    root: /path/to/project
    layout: even-horizontal
    panes:
      - commands:
        - asdf local ruby 2.6.1
        - asdf local nodejs 9.11.2
        - lsof -t -i tcp:3000 | xargs kill
        - redis-cli flushall
        - sleep 4
        - bundle exec rails s
      - commands:
        - asdf local ruby 2.6.1
        - asdf local nodejs 9.11.2
        - lsof -t -i tcp:3035 | xargs kill
        - bundle exec ./bin/webpack-dev-server

  - name: workers
    root: /path/to/project
    layout: main-vertical
    panes:
      - commands:
        - asdf local ruby 2.6.1
        - asdf local nodejs 9.11.2
        - redis-cli flushall
        - sleep 8
        - bundle exec sidekiq -C config/sidekiq.yml
