# TODO: delete this file and update the multiplier strategy in app/models/province.rb
#       after all campaigns with a start_date before 2019-03-07 have completed
"AE": 0.98
"AL": 0.28
"AM": 0.48
"AR": 0.22
"AT": 0.98
"AU": 0.95
"BD": 0.21
"BE": 0.31
"BG": 0.29
"BH": 0.1
"BO": 0.19
"BR": 0.11
"BS": 0.23
"BZ": 0.43
"CA": 0.71
"CH": 0.79
"CL": 0.84
"CN": 0.05
"CO": 0.17
"CR": 0.27
"DE": 0.69
"DK": 0.43
"DO": 0.6
"DZ": 0.44
"EC": 0.18
"EG": 0.35
"ES": 0.5
"FI": 0.67
"FR": 0.36
"GB": 0.87
"GR": 0.54
"GY": 0.15
"HR": 0.37
"HU": 0.22
"ID": 0.38
"IE": 0.6
"IL": 0.45
"IN": 0.23
"IS": 0.56
"IT": 0.75
"JM": 0.67
"JO": 0.27
"JP": 0.53
"KE": 0.26
"KH": 0.49
"KR": 0.28
"KW": 0.36
"LB": 0.53
"LK": 0.23
"LR": 0.08
"LT": 0.14
"LU": 0.18
"LV": 0.1
"LY": 0.36
"MA": 0.22
"MD": 0.08
"ME": 0.14
"MK": 0.39
"MU": 0.19
"MX": 0.5
"MY": 0.25
"NA": 0.16
"NI": 0.39
"NL": 0.44
"NO": 0.66
"NP": 0.43
"NZ": 0.86
"OM": 0.39
"PA": 0.31
"PE": 0.29
"PH": 0.25
"PK": 0.16
"PL": 0.19
"PT": 0.56
"QA": 0.19
"RO": 0.31
"RS": 0.05
"RU": 0.16
"RW": 0.38
"SA": 0.4
"SE": 0.51
"SG": 0.42
"SI": 0.08
"SK": 0.2
"SO": 0.08
"SV": 0.27
"TH": 0.42
"TN": 0.26
"TR": 0.68
"TT": 0.39
"TZ": 0.12
"UA": 0.08
"UG": 0.31
"US": 1
"UY": 0.26
"VE": 0.12
"VN": 0.24
"ZA": 0.45
"ZW": 0.27
