common: &defaults
  key: <%= SCOUT_KEY %>
  name: CodeFund
  monitor: true
  ignore:
    - '/okcomputer'
    - '/okcomputer.json'
    - '/okcomputer/all'
    - '/okcomputer/all.json'

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false

production:
  <<: *defaults
